### PR TITLE
fix HTML title + logo as SVG

### PR DESCRIPTION
**Pull request by jschroeter**
this fixes the HTML title of the wifimanager portal by adding the logo as inline SVG in CSS.

Since I don't have the font installed that it used in https://github.com/gdoor-org/gdoor-org.github.io/blob/d408e10103a08ccb7faadb3d52b921d02b86e590/_src/logo/logo.svg it looks a bit different. @DaSchaef, could you convert all text to paths and export the SVG again, so the SVG renders nicely also when the font isn't locally installed? Then we could use the SVG instead of the JPG/PNG in all places (incl. the website).

### CODE REVIEW

**Comment by DaSchaef** [comment]
I deleted the logo source files by mistake, but they were in the git history.

Do these files help (created with Inkscape under Linux)?

https://github.com/gdoor-org/gdoor-org.github.io/tree/main/assets/images/logo

**Comment by jschroeter** [comment]
Thanks, yes, that was helpful. I added a highly optimized SVG here: https://github.com/gdoor-org/gdoor-org.github.io/tree/main/assets/images/logo
It's now used everywhere.

Not sure what these files are there for: https://github.com/gdoor-org/gdoor-org.github.io/tree/main/_src/logo ?

**Comment by DaSchaef** [comment]
Hm, I forgot this folder :sweat_smile: 
Should be identical or maybe an inkscape export of it?

**Comment by jschroeter** [comment]
I did some cleanup: https://github.com/gdoor-org/gdoor-org.github.io/commit/7537c4d5f23bb5b8330bec0f7405db067c2c32f7

**Pull request merged**
