### PR TITLE
add docs for Home Assistant integration

### PR DESCRIPTION
**Pull request by jschroeter**

### CODE REVIEW

**Comment by DaSchaef** [comment]
Good points!
Merge as-is or should we maybe move Home Assistent to the root and the protocol to a sub page?

Small things:
- You mentioned to use the "hexvalue" field for sending, but it is not in the JSON example.
- We (You / I) can also update the protocol doc with the "call accept video" and remove the "audio" on HW type
- The adapter was also successfully tested with: :-)
   - Steuergerät Audio 1287 00
   - Wohnungsstation AP 1250 ..

FYI:
I do not know if you can always depend on the `parameter` field only, most likely you can - but I'm not 100% sure about it.
To capture all bus installation situations you may need to check:
- source
- action
- parameters

(These are also the fields which Gira devices check, e.g. they ignore the "type" field)

**Comment by DaSchaef** [comment]
To the parameter field: Another warning, we also noticed that sometimes the second byte had two different values send by the outdoor station (still not fully understood).

**Comment by DaSchaef** [comment]
And one last thing: I need to update the protocol description once we merge the JSON update, so that the naming and format is consistent between Homeassistent, ESP Code, MQTT and protocol description. :see_no_evil:

**Comment by jschroeter** [comment]
I like the idea of moving the protocol into an own file and did it.

I also addressed some more things, but didn't add the video part yet - will do this in a separate PR as I still need to investigate a bit what exactly is happening on the bus. And yes, we should sync the wording in docs & code.

Regarding the parameters I'm also not 100% sure yet, let's see :-)

I would say let's merge this PR now and improve on the go. Please hit the button if you agree with the changes.

**Pull request merged**
